version: '2'
services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html/
    depends_on:
      - mariadb